version: "3.3"
services:
    app:
        image: nit-archive-backend:latest
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - /nit/backend/storage:/app/.nit
        networks:
            - net
            - traefik-public
        depends_on:
            - mysql
            - redis
        env_file: backend.env
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.backend-http.service=backend
                - traefik.http.routers.backend-https.service=backend
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.routers.backend-https.rule=Host(`${BACKEND_DOMAIN}`)
                - traefik.http.routers.backend-https.entrypoints=https
                - traefik.http.routers.backend-http.rule=Host(`${BACKEND_DOMAIN}`)
                - traefik.http.routers.backend-http.entrypoints=http
                - traefik.http.routers.backend-http.middlewares=https-redirect
                - traefik.http.services.backend.loadbalancer.server.port=3000
                - traefik.http.routers.backend-https.tls=true
                - traefik.http.routers.backend-https.tls.certresolver=le
    admin:
        image: phpmyadmin/phpmyadmin
        networks:
            - net
            - traefik-public
        depends_on:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - TZ=Asia/Tehran
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.pma-http.service=pma
                - traefik.http.routers.pma-https.service=pma
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.routers.pma-https.rule=Host(`${PMA_DOMAIN}`)
                - traefik.http.routers.pma-https.entrypoints=https
                - traefik.http.routers.pma-http.rule=Host(`${PMA_DOMAIN}`)
                - traefik.http.routers.pma-http.entrypoints=http
                - traefik.http.routers.pma-http.middlewares=https-redirect
                - traefik.http.services.pma.loadbalancer.server.port=80
                - traefik.http.routers.pma-https.tls=true
                - traefik.http.routers.pma-https.tls.certresolver=le
    redis:
        image: redis:alpine
        command: --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT_NUMBER=6379
            - TZ=Asia/Tehran
        volumes:
            - /nit/redis:/data
        networks:
            - net
    mysql:
        image: mysql:8
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
            - MYSQL_ALLOW_EMPTY_PASSWORD=ok
            - TZ=Asia/Tehran
        volumes:
            - /nit/mysql:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
        networks:
            - net
networks:
    net:
        driver: overlay
        attachable: true
    traefik-public:
        external: true
